apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: default
spec:
  selector:
    app: catalogue
  ports:
  - name: grpc-catalogue
    protocol: TCP
    port: 50051
    targetPort: 50051
