apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: catalogue
  namespace: default
spec:
  host: catalogue
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 30s
  subsets:
  - name: v1
    labels:
      version: v1