apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: default
  labels:
    app: shipping
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
      version: v1
  template:
    metadata:
      labels:
        app: shipping
        version: v1
    spec:
      containers:
      - name: shipping
        image: registry.gitlab.com/gihyo-ms-dev-book/showcase/all-in-one/application/shipping
        env:
        - name: RABBITMQ
          value: "amqp://guest:guest@rabbitmq:5672/"
        ports:
        - containerPort: 5672
