apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: default
  labels:
    app: order
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      containers:
      - name: order
        image: registry.gitlab.com/gihyo-ms-dev-book/showcase/all-in-one/application/order
        env:
        - name: DATABASE
          value: "mongodb://order-db:27017/orders"
        - name: RABBITMQ
          value: "amqp://guest:guest@rabbitmq:5672/"
        ports:
        - containerPort: 50052
        livenessProbe:
          grpc:
            port: 50052
          initialDelaySeconds: 10
        readinessProbe:
          grpc:
            port: 50052
          initialDelaySeconds: 10
