apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: default
  labels:
    app: order-db
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
      version: v1
  template:
    metadata:
      labels:
        app: order-db
        version: v1
    spec:
      containers:
      - name: order-db
        image: registry.gitlab.com/gihyo-ms-dev-book/showcase/all-in-one/application/order-db
        ports:
        - containerPort: 27017
