apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: default
  labels:
    app: catalogue
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      version: v1
  template:
    metadata:
      labels:
        app: catalogue
        version: v1
    spec:
      containers:
      - name: catalogue
        image: registry.gitlab.com/gihyo-ms-dev-book/showcase/all-in-one/application/catalogue
        env:
        - name: DATABASE
          value: "catalogue_user:default_password@tcp(catalogue-db:3306)/booksdb"
        ports:
        - containerPort: 50051
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
