apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    app: rabbitmq
  ports:
    # the port that this service should serve on
  - port: 5672
    name: tcp-rabbitmq
    targetPort: 5672
